runtime: python39 # or another supported version

instance_class: F2

handlers:
# Matches requests to /images/... to files in static/images/...
- url: /
  static_files: index.html
  upload: index.html
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
- url: /poll/js/matchScript.js
  static_files: js/matchScript.js
  upload: js/matchScript.js
- url: /poll/match.html
  static_files: match.html
  upload: match.html
- url: /poll/image
  static_dir: image
- url: /assets
  static_dir: assets
- url: /engine
  static_dir: engine
- url: /js
  static_dir: js
- url: /style
  static_dir: style
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
