runtime: python39 # or another supported version

service: api
instance_class: F2

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "la-hacks-gamers-firebase-adminsdk-bm7jf-211c6a0f92.json"

handlers:
# Matches requests to /images/... to files in static/images/...
- url: /images
  static_dir: static/images

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
